name: ips_events_manager
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  meta_components:
    path: meta_components
  repositories:
    path: repositories
  repository_collection:
    path: repository_collection
  core_components:
    path: "core_components"
  flow_builder: ^0.0.4
  shrink_sidemenu: ^2.0.0+2-null-safety
  salomon_bottom_bar: ^3.3.1
  equatable: ^2.0.3
  firebase_core: ^1.19.1
  firebase_analytics: ^9.1.12

dev_dependencies:
  build_runner: ^2.0.6 #provides a concrete way of generating files
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

dependency_overrides:
  flutter_secure_storage: 5.0.2
  
flutter:
  uses-material-design: true
  generate: true
