name: repositories
description: Package that contains the repositories of the Portuguese Brand app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  aad_oauth: ^0.4.0
  core_components:
      path: ../core_components
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  meta_components:
    path: ../meta_components  
  permission_handler: ^9.2.0
  

dev_dependencies:
  build_runner: ^2.1.5  
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4 #Provides Dart Build System builders for handling JSON  
  retrofit_generator: ^4.0.1
  very_good_analysis: ^2.4.0
  
dependency_overrides:
  flutter_secure_storage: 5.0.2