// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQh8oglcjKNmDvcsz3umzVWShi7ym-Ktc',
    appId: '1:1087071113834:web:2247361745a1d09e28b013',
    messagingSenderId: '1087071113834',
    projectId: 'ips-events-manager',
    authDomain: 'ips-events-manager.firebaseapp.com',
    storageBucket: 'ips-events-manager.appspot.com',
    measurementId: 'G-Y6P4L847X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrA0fqqNY7LZekFRzAVHKjEUSlpDy1x0',
    appId: '1:1087071113834:android:f4d1e0e421e651cc28b013',
    messagingSenderId: '1087071113834',
    projectId: 'ips-events-manager',
    storageBucket: 'ips-events-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASchRTBb9WT0wq_uaQtFihbLGv2B7pz7c',
    appId: '1:1087071113834:ios:38eed22e57607ae028b013',
    messagingSenderId: '1087071113834',
    projectId: 'ips-events-manager',
    storageBucket: 'ips-events-manager.appspot.com',
    androidClientId: '1087071113834-7671mt2t7ce2umtbugu4in4cf7qcdjlu.apps.googleusercontent.com',
    iosClientId: '1087071113834-lg8il9gqhcouv7d2q9jvcgbb1nt7p8k4.apps.googleusercontent.com',
    iosBundleId: 'com.ips-events-manager',
  );
}
